"use client";

import { useCallback, useEffect, useMemo, useRef, useState } from "react";
import { useMotionValueEvent, useReducedMotion, useScroll, useTransform } from "framer-motion";
import type { AnimalEvent } from "@/types/event";
import { TimelineTrack } from "./TimelineTrack";
import { TimelineProgress } from "./TimelineProgress";
import { TimelineNavigation } from "./TimelineNavigation";
import { EventDetailDrawer } from "@/components/event/EventDetailDrawer";
import { useLanguage } from "@/components/ui/LanguageProvider"; import { ui } from "@/lib/i18n";

export function HorizontalTimeline({ events }: { events: AnimalEvent[] }) {
  const {locale}=useLanguage(); const t=ui[locale];
  const sectionRef = useRef<HTMLElement>(null); const viewportRef = useRef<HTMLDivElement>(null); const trackRef = useRef<HTMLDivElement>(null); const closeTimer = useRef<number | null>(null); const openTimer = useRef<number | null>(null); const returnFocus = useRef<HTMLElement | null>(null);
  const reducedMotion = useReducedMotion(); const [maxX, setMaxX] = useState(0); const [isMobile, setIsMobile] = useState(false); const [openId, setOpenId] = useState<string | null>(null); const [detailId, setDetailId] = useState<string | null>(null); const [activeIndex, setActiveIndex] = useState(0); const [mobileProgress, setMobileProgress] = useState(0);
  const { scrollYProgress } = useScroll({ target: sectionRef, offset: ["start start", "end end"] }); const x = useTransform(scrollYProgress, [0, 1], [0, reducedMotion ? 0 : -maxX]); const drawerEvent = events.find((event) => event.id === detailId) ?? null; const progress = isMobile ? mobileProgress : Math.max(0, Math.min(1, activeIndex / Math.max(1, events.length - 1)));
  useEffect(() => { const media = window.matchMedia("(max-width: 760px)"); const sync = () => setIsMobile(media.matches || Boolean(reducedMotion)); sync(); media.addEventListener("change", sync); return () => media.removeEventListener("change", sync); }, [reducedMotion]);
  useEffect(() => { const measure = () => setMaxX(Math.max(0, (trackRef.current?.scrollWidth ?? 0) - (viewportRef.current?.clientWidth ?? 0))); const observer = new ResizeObserver(measure); if (trackRef.current) observer.observe(trackRef.current); if (viewportRef.current) observer.observe(viewportRef.current); measure(); return () => observer.disconnect(); }, [events.length, isMobile]);
  useMotionValueEvent(scrollYProgress, "change", (value) => { if (!isMobile) setActiveIndex(Math.min(events.length - 1, Math.max(0, Math.round(value * (events.length - 1))))); });
  const clearTimers = () => { if (closeTimer.current) window.clearTimeout(closeTimer.current); if (openTimer.current) window.clearTimeout(openTimer.current); };
  const openBoard = useCallback((id: string) => { if (closeTimer.current) window.clearTimeout(closeTimer.current); if (openTimer.current) window.clearTimeout(openTimer.current); openTimer.current = window.setTimeout(() => setOpenId(id), 120); }, []);
  const closeBoard = useCallback(() => { if (openTimer.current) window.clearTimeout(openTimer.current); closeTimer.current = window.setTimeout(() => setOpenId(null), 180); }, []);
  const showDetail = useCallback((event: AnimalEvent, anchor: HTMLElement) => { clearTimers(); setOpenId(null); returnFocus.current = anchor; setDetailId(event.id); }, []);
  const closeDetail = useCallback(() => { setDetailId(null); window.setTimeout(() => returnFocus.current?.focus(), 0); }, []);
  useEffect(() => { const escape = (e: KeyboardEvent) => { if (e.key === "Escape" && !detailId) setOpenId(null); }; const outside = (e: PointerEvent) => { if (isMobile && openId && !(e.target as Element).closest("[data-event-index], [data-info-board]")) setOpenId(null); }; document.addEventListener("keydown", escape); document.addEventListener("pointerdown", outside); return () => { clearTimers(); document.removeEventListener("keydown", escape); document.removeEventListener("pointerdown", outside); }; }, [detailId, isMobile, openId]);
  useEffect(() => { if (isMobile) return; const onKey = (e: KeyboardEvent) => { const rect = sectionRef.current?.getBoundingClientRect(); if (!rect || rect.top > 1 || rect.bottom < window.innerHeight - 1 || !["ArrowLeft", "ArrowRight"].includes(e.key)) return; e.preventDefault(); const direction = e.key === "ArrowRight" ? 1 : -1; window.scrollBy({ top: direction * Math.max(260, maxX / Math.max(1, events.length - 1)), behavior: reducedMotion ? "auto" : "smooth" }); }; window.addEventListener("keydown", onKey); return () => window.removeEventListener("keydown", onKey); }, [events.length, isMobile, maxX, reducedMotion]);
  const onMobileScroll = () => { if (!viewportRef.current) return; const el = viewportRef.current; const p = el.scrollLeft / Math.max(1, el.scrollWidth - el.clientWidth); setMobileProgress(p); setActiveIndex(Math.min(events.length - 1, Math.round(p * (events.length - 1)))); setOpenId(null); };
  const height = isMobile ? undefined : Math.max(1400, maxX + (typeof window !== "undefined" ? window.innerHeight : 900)); const drawerIndex = useMemo(() => events.findIndex((event) => event.id === detailId), [detailId, events]);
  return <section ref={sectionRef} className={`timeline-section ${isMobile ? "is-mobile" : ""}`} style={height ? { height } : undefined} aria-labelledby="timeline-heading"><h2 id="timeline-heading" className="sr-only">{t.timeline}</h2><div ref={viewportRef} className="timeline-viewport" onScroll={isMobile ? onMobileScroll : undefined}><div className="timeline-chrome"><p>{t.archive}</p><TimelineProgress index={activeIndex} total={events.length} year={events[activeIndex]?.date.slice(0,4) ?? "—"} progress={progress} /><TimelineNavigation /></div><TimelineTrack events={events} trackRef={trackRef} x={x} openId={openId} isMobile={isMobile} onOpenBoard={openBoard} onCloseBoard={closeBoard} onBoardEnter={clearTimers} onBoardLeave={closeBoard} onOpenDetail={showDetail} /></div><p className="mobile-swipe" aria-hidden="true">{t.swipe}</p><EventDetailDrawer event={drawerEvent} previous={drawerIndex > 0 ? events[drawerIndex - 1] : undefined} next={drawerIndex >= 0 && drawerIndex < events.length - 1 ? events[drawerIndex + 1] : undefined} onClose={closeDetail} onNavigate={(event) => setDetailId(event.id)} /></section>;
}
